#!/usr/bin/env python3
"""Regenerate every screenshot in the documentation.

The images in `docs/images/` are build output, not assets: they are rendered
from the synthetic source, which needs no camera, no trained model and no
dataset, so anyone cloning this repository can reproduce them exactly. That is
deliberate. A screenshot pasted into a README rots the moment the renderer
changes and nobody notices; one that is regenerated by a command is checked
every time somebody runs it.

    tools/screenshots.py                 # all of them
    tools/screenshots.py --only song     # one

The song shots need the [score] extra and a Guitar Pro file; they are skipped
with a note if `--song` is not given, rather than failing the whole run.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fretguide import render  # noqa: E402
from fretguide.content import resolve_selection  # noqa: E402
from fretguide.geometry import grid_lines  # noqa: E402
from fretguide.menu import Layout, Menu, preferred_anchor  # noqa: E402
from fretguide.source import open_source  # noqa: E402
from fretguide.types import Selection  # noqa: E402

WIDTH, HEIGHT = 1600, 900
MAX_FRET = 21

#: name -> (selection, caption, options)
SHOTS: list[dict] = [
    dict(key="chord", sel=Selection("chord", "C"),
         note="An open C. Muted strings get a cross, open ones a ring."),
    dict(key="mode-box", sel=Selection("mode_box", "G:2"),
         note="Dorian in the key of G, as a box with finger numbers."),
    dict(key="pentatonic", sel=Selection("penta_box", "A:1:min"),
         note="First shape of A minor pentatonic."),
    dict(key="whole-neck", sel=Selection("scale_generated", "A minor pentatonic"),
         note="The same scale across the whole neck, roots picked out."),
    dict(key="menu", sel=Selection("mode_box", "G:2"), menu=True,
         note="The practice catalogue, browsed as columns."),
    dict(key="no-lock", sel=Selection("chord", "C"), refuse=True,
         note="The trust gate refusing to draw."),
    dict(key="grid", sel=Selection("chord", "C"), debug=True,
         note="Every fret and string the pose implies."),
]


def board_crop(pad=0.09, aspect=16 / 9) -> tuple[int, int, int, int]:
    """The rectangle the neck actually occupies, once, for every shot.

    The synthetic board is drawn small in a wide frame, so a full-frame
    screenshot is mostly empty desk. Cropping to the same rect in every image
    also means the neck is the same size across the whole README, which a
    per-image crop would not give.
    """
    src = open_source("synthetic", width=WIDTH, height=HEIGHT, fps=None, max_fret=MAX_FRET)
    packet = src.read()
    src.close()
    pts = np.array([[q.x, q.y] for line in grid_lines(packet.H, MAX_FRET) for q in line])
    x0, y0 = pts.min(axis=0)
    x1, y1 = pts.max(axis=0)
    mx, my = (x1 - x0) * pad, (y1 - y0) * pad
    x0, y0, x1, y1 = x0 - mx, y0 - my, x1 + mx, y1 + my
    # Grow the short side to hold the aspect ratio rather than squashing.
    w, h = x1 - x0, y1 - y0
    if w / h < aspect:
        extra = (h * aspect - w) / 2
        x0, x1 = x0 - extra, x1 + extra
    else:
        extra = (w / aspect - h) / 2
        y0, y1 = y0 - extra, y1 + extra
    return (max(0, int(x0)), max(0, int(y0)),
            min(WIDTH, int(x1)), min(HEIGHT, int(y1)))


CROP = None

#: The synthetic backdrop is procedural noise, which PNG cannot compress -- the
#: shots came out at 900 kB each, 7 MB for a README. At this size the overlay is
#: flat colour on a soft background and JPEG is indistinguishable, so the images
#: ship at a twentieth of the size.
JPEG_QUALITY = 92


def write(path: Path, view) -> None:
    cv2.imwrite(str(path.with_suffix(".jpg")), view,
                [cv2.IMWRITE_JPEG_QUALITY, JPEG_QUALITY])


def frame(src, sel, resolved, *, menu=False, debug=False, max_fret=MAX_FRET, crop=True, skip=0):
    for _ in range(skip):
        src.read()
    packet = src.read()
    view = packet.to_bgr()
    if packet.H is not None:
        render.draw_grid(view, packet.H, max_fret)
        if debug:
            render.draw_debug(view, packet.H, max_fret, packet.debug_pts)
        render.draw_selection(view, packet.H, resolved)
    else:
        render.dim(view, 0.5)
    if crop and not menu:
        # Crop before the HUD, so the caption stays welded to the image corner
        # instead of drifting off with the video.
        x0, y0, x1, y1 = CROP
        view = np.ascontiguousarray(view[y0:y1, x0:x1])
    render.draw_hud(view, packet.status, resolved.name, 30.0, extra="synthetic neck")
    if menu:
        pts = None
        if packet.H is not None:
            pts = np.array([[q.x, q.y] for line in grid_lines(packet.H, max_fret) for q in line])
        m = Menu(max_fret=max_fret)
        m.open = True
        m.sync_to(sel, keep_focus=False)
        render.draw_menu(view, m, Layout.for_frame(WIDTH, HEIGHT,
                                                   preferred_anchor(pts, WIDTH, HEIGHT, m)))
    return view


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("docs/images"))
    ap.add_argument("--only", default=None, help="render just this one")
    ap.add_argument("--song", type=Path, default=None, help="a Guitar Pro file for the song shots")
    ap.add_argument("--track", type=int, default=None)
    ap.add_argument("--beat", type=float, default=8.0)
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    global CROP
    CROP = board_crop()

    made = []
    for shot in SHOTS:
        if args.only and shot["key"] != args.only:
            continue
        src = open_source("synthetic", width=WIDTH, height=HEIGHT, fps=None,
                          max_fret=MAX_FRET, refuse_every=1 if shot.get("refuse") else 0)
        resolved = resolve_selection(shot["sel"], max_fret=MAX_FRET)
        if resolved is None:
            print(f"  ! unknown selection for {shot['key']}")
            src.close()
            continue
        view = frame(src, shot["sel"], resolved,
                     menu=shot.get("menu", False), debug=shot.get("debug", False),
                     # SyntheticSource never refuses frame 0 (`and i` in its guard),
                     # so the NO LOCK shot has to ask for the next one -- otherwise
                     # it silently renders a normal frame and looks like a success.
                     skip=1 if shot.get("refuse") else 0)
        src.close()
        path = args.out / f"{shot['key']}.jpg"
        write(path, view)
        made.append(path)

    if args.song and (not args.only or args.only == "song"):
        from fretguide.score import read_guitarpro
        from fretguide.transport import Transport
        song = read_guitarpro(args.song)
        track = (song.tracks[args.track] if args.track is not None
                 else next(t for t in song.tracks if t.playable))
        play = Transport(song=song, track=track, beat=args.beat, playing=True)
        src = open_source("synthetic", width=WIDTH, height=HEIGHT, fps=None, max_fret=MAX_FRET)
        view = frame(src, None, play.resolved())
        src.close()
        path = args.out / "song.jpg"
        write(path, view)
        made.append(path)
    elif not args.only:
        print("  (no --song given, skipping the song shot)")

    for p in made:
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
