server.port=8080
spring.application.name=code-reviewer

mistral.api.key=${MISTRAL_API_KEY:boetgzYk2iC3W4z6jqC9RlOeNHB5QkM9}
mistral.api.url=https://api.mistral.ai/v1/chat/completions
mistral.model=mistral-small-latest
